### ISSUE TITLE
BUG - All Xero Dbt jobs failing due to missing table

### ISSUE THREAD

**Issue by elucidateadmin** [fivetran/dbt_xero#10]
**Are you a current Fivetran customer?** 
Yes. Shubham Sinha, Head of Engineering, Daydream

**Describe the bug**
dbt run fails since, table credit_note doesn't exist for three separate accounts. There are no config vars that I could use to add a true/false flag to skip this table.

Attaching Bug report from dbt run:
```
Database Error in model stg_xero__credit_note_tmp (models/tmp/stg_xero__credit_note_tmp.sql)
  relation "trainwithkickoff_39_xero.credit_note" does not exist
  LINE 4:     select * from "cloud_services"."trainwithkickoff_39_xero...
                            ^
  compiled SQL at target/run/xero_source/models/tmp/stg_xero__credit_note_tmp.sql
```

**Steps to reproduce**
Hard to reproduce this locally unless you have the same setup (account, tables) but I believe the bug description should have all the details. 

**Expected behavior**
Possible to create some config vars that can be used to skip this table?

**Project variables configuration**

```yml
vars:
  xero_schema: trainwithkickoff_39_xero
  xero_database: cloud_services

models:
  xero:
    +schema: transformations
```

**Package Version**
```yml
packages:
  - package: fivetran/xero
    version: 0.1.1
```

**Warehouse**

- [ ] BigQuery
- [ ] Redshift
- [ ] Snowflake
- [X] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Additional context**
 

**Screenshots**
Attaching all the tables synced from Account 1 (Real production users):
<img width="515" alt="Screen Shot 2021-06-22 at 1 10 58 AM" src="https://user-images.githubusercontent.com/65250625/122888424-b5ded700-d2f6-11eb-932a-2c462273e7c8.png">

Attaching all the tables synced from Account 2 (Real production users):
<img width="665" alt="Screen Shot 2021-06-22 at 1 19 38 AM" src="https://user-images.githubusercontent.com/65250625/122889753-ebd08b00-d2f7-11eb-8b66-b0da23a7f4fd.png">

**Please indicate the level of urgency** 
It's pretty critical for us as it affects several Production users.

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [X] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [ ] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @elucidateadmin, thanks for opening this Issue!

Our decision to not include a variable to disable the credit_note models was due to >90% of our customers having this. However, we do not want the other 10% to have their dbt runs fails because they do not have this table. Therefore, I just created a new branch and pushed recent commits to add a variable to disable the credit_note models if a users does not have the source table. 

I have tested this on my end and it works, but would greatly appreciate if you had time to test the working branch on a customer of yours and let me know if you see the expected results. You can use the below config within your `packages.yml` in place of the dependency you currently have for fivetran/dbt_xero.
```yml
- git: https://github.com/fivetran/dbt_xero.git
    revision: feature/credit-note-var
    warn-unpinned: false
```

Additionally, you can use the below config in your variables block to disable the credit_note models.

```yml
vars:
    xero__using_credit_note: false
```

Let me know if you have any issues with the working branch or if you have any questions. Thanks!

**Comment by elucidateadmin** [comment]
Hey @fivetran-joemarkiewicz  your fix worked and I tested it against both of our production accounts! Thanks

**Comment by fivetran-joemarkiewicz** [comment]
@elucidateadmin I just merged the branch and cut a new release of the xero package! The new `v0.1.2` release should be live by the end of the day on the dbt hub. 

Thanks again for opening this issue and let me know if you encounter any other issues or questions!
