### ISSUE TITLE
BUG - Reports generated from the Zero DBT package has the wrong net_amount

### ISSUE THREAD

**Issue by farhatOnplan** [fivetran/dbt_xero#14]
**Are you a current Fivetran customer?** 
Yes. Farhat Khan, Onplan Co

**Describe the bug**
We have a Xero connector for our client in Fivetran, our requirement is to fetch reports from Xero, but Fivetran is only receiving schemas, not reports, so for generating reports like Balance Sheet, Profit and Loss, Trial Balance, etc. For this, we are using the Fivetran Zero DBT package. But the report generated through the Fivetran DBT package has the wrong net_amount, all net_amount in the report are wrong. 

**Steps to reproduce**
1. Go to the Fivetran dashboard and create a connector using Xero as the source and BigQuery as the destination.
2. add transformation for connector using Fivetran Xero DBT package.
3. after running synch you will get reports generated through the DBT package in BigQuery.
4. Now Just compare reports value with original Xero reports.

**Expected behavior**
Reports generated through Fivetran should have the same value as original Xero reports.

**Project variables configuration**

name: 'five_tran_xero'
version: '0.2.0'
config-version: 2
require-dbt-version: [">=0.20.0"]

vars:
  xero_schema: five_tran_xero
  xero_database: etl_data_base
  five_tran_xero:
    account: "{{ ref('stg_xero__account') }}" 
    contact: "{{ ref('stg_xero__contact') }}" 
    invoice_line_item: "{{ ref('stg_xero__invoice_line_item') }}" 
    invoice: "{{ ref('stg_xero__invoice') }}" 
    journal_line: "{{ ref('stg_xero__journal_line') }}" 
    journal: "{{ ref('stg_xero__journal') }}" 
    organization: "{{ ref('stg_xero__organization') }}" 
    credit_note: "{{ ref('stg_xero__credit_note') }}" 
    bank_transaction: "{{ ref('stg_xero__bank_transaction') }}" 

models:
  five_tran_xero:
    +materialized: table
    +schema: xero

**Package Version**

packages:
  - package: fivetran/xero_source
    version: [">=0.2.0","<0.3.0"]

**Warehouse**

 
- [x] BigQuery
- [ ] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Additional context**
 

**Screenshots**
can't provide due to the data security

**Please indicate the level of urgency** 
This is really important because, the client needs the report, but as I told the report we are generating through the Fivetran DBT package has the wrong net_amount which is blocking us. This will really affect our relationship with the customer. If we don't deliver it on time it may result in fine also.

**Are you interested in contributing to this package?** 
No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @farhatOnplan thank you for opening this issue and raising this to our attention.

Would you be able to provide some more context as to how these net amounts are off? It would be helpful if you would be able to provide a comparison of the net_amount being off between the model output and the Xero report for a given account and range.

As you are not able to share these via github it would be great if you could share the additional context via email (solutions@fivetran.com) and our team may coordinate with you from there. Otherwise it would most likely be helpful if you could schedule some time with our team during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours?month=2021-09) where we can debug live.

**Comment by farhatOnplan** [comment]
> Hi @farhatOnplan thank you for opening this issue and raising this to our attention.
> 
> Would you be able to provide some more context as to how these net amounts are off? It would be helpful if you would be able to provide a comparison of the net_amount being off between the model output and the Xero report for a given account and range.
> 
> As you are not able to share these via github it would be great if you could share the additional context via email ([solutions@fivetran.com](mailto:solutions@fivetran.com)) and our team may coordinate with you from there. Otherwise it would most likely be helpful if you could schedule some time with our team during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours?month=2021-09) where we can debug live.

Ok, yes sure
I'll send you more details and comparison of values via email.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @farhatOnplan thanks for sending over the additional information! I have been able to take a quick look and think there may be a misunderstanding. Our `xero__balance_sheet` model represents the state of the balance sheet for a given account on a given month. 

In the case of the data you provided it looks like you are looking at September. The dbt model output you are looking at provides the totals for *only* for September 2021. However, it looks like the Balance Sheet report you were able to generate from Xero shows totals for the accounts "As of September 1, 2021". My interpretation of this is that the totals are summed for all previous months from the start up to September 1, 2021 instead of being *just* for September, 2021.

You may be able to match to totals if you sum the balance sheet totals within the dbt_xero output up to August. This way you will include all previous months leading up to September 1st, 2021.

Let me know if this helps! Otherwise, you can always schedule time during out [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours?month=2021-09) where we may debug this live.

**Comment by fivetran-joemarkiewicz** [comment]
@farhatOnplan thank you so much for providing the additional detail!

I have been able to look into the comparison of the Xero generated report and also the dbt_xero output balance sheet model. I have been able to successfully match the totals for a number of the accounts, but then have found a few that vary in their deltas. As there doesn't seem to be a trend in how this data discrepancy is occuring I feel it would be best to setup a call with you to dive a bit deeper into this bug. I will reach back out so we may coordinate a time next week for us to meet and debug live.

Thank you!

**Comment by fivetran-joemarkiewicz** [comment]
@farhatOnplan another thought I just thought of is that the Xero Balance Sheet report you provided states that it is 

> As of September 1, 2021

While the dbt_xero `xero__balance_sheet` report 

> Represents the state of the balance sheet for a given account on a given month.

With that, my thought is that the varying discrepancies could be due to the fact that they are off by one month? The dbt_xero package includes the entire month of September, while the Xero report does not. It could be worth querying the month of August to get the entire data up to September 1st from the data output by the dbt package. Let me know if that helps!

**Comment by fivetran-joemarkiewicz** [comment]
It was great chatting with you @farhatOnplan! 

After we dug into the dbt package report and the Xero UI report we found the following:
- The Xero report was limited to only the first of September and the dbt package was looking at September up until the point of the dbt package being run. Once we narrowed focus on the end of August for both reports we saw accounts tying out.
- There is a minor delay between current month transactions being synced from Xero to the warehouse with Fivetran. As such, once we ignored the current month (September) we saw accounts tying out.
- The dbt package reports the **closing** balance. Once you focus on the closing balance and not the opening balance you are able to tie accounts out.
- If you want a balance sheet report of a specific account for a period of time (ie. From January 2021 to August 2021) you may sum the closing balances within the dbt package of an account to arrive at that total balance for the desired date range. By default the dbt package will sum for the designated month.

It was great chatting with you and digging into these nuances @farhatOnplan. I will close this issue as we were able to resolve the discrepancies. Feel free to open a new issue if you encounter any other bugs or a feature request if you would like our team to scope out any future enhancements to the package!
